apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mapspiral/argo-cd-sandbox.git
    targetRevision: main
    path: src/argo-cd-kustomize/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: mapspiral
  syncPolicy:
    automated: {}