apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-application
    spec:
      containers:
      - image: <image-name>:<tag>
        name: example-application
        ports:
        - containerPort: 8080
  template:
    spec:
      containers:
      - image: mapspiral/gitops-application:v1
        name: gitops-application
